// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ve.gob.iribarren.tube.model;

import org.springframework.beans.factory.annotation.Configurable;
import ve.gob.iribarren.tube.model.ConfigLiveJwplayerIntegrationTest;

privileged aspect ConfigLiveJwplayerIntegrationTest_Roo_Configurable {
    
    declare @type: ConfigLiveJwplayerIntegrationTest: @Configurable;
    
}
