// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ve.gob.iribarren.tube.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ve.gob.iribarren.tube.model.ConfigLiveJwplayerDataOnDemand;
import ve.gob.iribarren.tube.model.ConfigLiveJwplayerIntegrationTest;
import ve.gob.iribarren.tube.repository.ConfigLiveJwplayerRepository;

privileged aspect ConfigLiveJwplayerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConfigLiveJwplayerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConfigLiveJwplayerIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConfigLiveJwplayerIntegrationTest: @Transactional;
    
    @Autowired
    ConfigLiveJwplayerDataOnDemand ConfigLiveJwplayerIntegrationTest.dod;
    
    @Autowired
    ConfigLiveJwplayerRepository ConfigLiveJwplayerIntegrationTest.configLiveJwplayerRepository;
    
    @Test
    public void ConfigLiveJwplayerIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to initialize correctly", dod.getRandomConfigLiveJwplayer());
        long count = configLiveJwplayerRepository.count();
        Assert.assertTrue("Counter for 'ConfigLiveJwplayer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConfigLiveJwplayerIntegrationTest.testFind() {
        ConfigLiveJwplayer obj = dod.getRandomConfigLiveJwplayer();
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to provide an identifier", id);
        obj = configLiveJwplayerRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ConfigLiveJwplayer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ConfigLiveJwplayer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConfigLiveJwplayerIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to initialize correctly", dod.getRandomConfigLiveJwplayer());
        long count = configLiveJwplayerRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ConfigLiveJwplayer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ConfigLiveJwplayer> result = configLiveJwplayerRepository.findAll();
        Assert.assertNotNull("Find all method for 'ConfigLiveJwplayer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ConfigLiveJwplayer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConfigLiveJwplayerIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to initialize correctly", dod.getRandomConfigLiveJwplayer());
        long count = configLiveJwplayerRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ConfigLiveJwplayer> result = configLiveJwplayerRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ConfigLiveJwplayer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ConfigLiveJwplayer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConfigLiveJwplayerIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to initialize correctly", dod.getRandomConfigLiveJwplayer());
        ConfigLiveJwplayer obj = dod.getNewTransientConfigLiveJwplayer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ConfigLiveJwplayer' identifier to be null", obj.getId());
        try {
            configLiveJwplayerRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        configLiveJwplayerRepository.flush();
        Assert.assertNotNull("Expected 'ConfigLiveJwplayer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConfigLiveJwplayerIntegrationTest.testDelete() {
        ConfigLiveJwplayer obj = dod.getRandomConfigLiveJwplayer();
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ConfigLiveJwplayer' failed to provide an identifier", id);
        obj = configLiveJwplayerRepository.findOne(id);
        configLiveJwplayerRepository.delete(obj);
        configLiveJwplayerRepository.flush();
        Assert.assertNull("Failed to remove 'ConfigLiveJwplayer' with identifier '" + id + "'", configLiveJwplayerRepository.findOne(id));
    }
    
}
