// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ve.gob.iribarren.tube.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ve.gob.iribarren.tube.model.MultimediaDataOnDemand;
import ve.gob.iribarren.tube.model.MultimediaIntegrationTest;
import ve.gob.iribarren.tube.repository.MultimediaRepository;

privileged aspect MultimediaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MultimediaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MultimediaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MultimediaIntegrationTest: @Transactional;
    
    @Autowired
    MultimediaDataOnDemand MultimediaIntegrationTest.dod;
    
    @Autowired
    MultimediaRepository MultimediaIntegrationTest.multimediaRepository;
    
    @Test
    public void MultimediaIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to initialize correctly", dod.getRandomMultimedia());
        long count = multimediaRepository.count();
        Assert.assertTrue("Counter for 'Multimedia' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MultimediaIntegrationTest.testFind() {
        Multimedia obj = dod.getRandomMultimedia();
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to provide an identifier", id);
        obj = multimediaRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Multimedia' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Multimedia' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MultimediaIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to initialize correctly", dod.getRandomMultimedia());
        long count = multimediaRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Multimedia', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Multimedia> result = multimediaRepository.findAll();
        Assert.assertNotNull("Find all method for 'Multimedia' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Multimedia' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MultimediaIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to initialize correctly", dod.getRandomMultimedia());
        long count = multimediaRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Multimedia> result = multimediaRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Multimedia' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Multimedia' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MultimediaIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to initialize correctly", dod.getRandomMultimedia());
        Multimedia obj = dod.getNewTransientMultimedia(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Multimedia' identifier to be null", obj.getId());
        try {
            multimediaRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        multimediaRepository.flush();
        Assert.assertNotNull("Expected 'Multimedia' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MultimediaIntegrationTest.testDelete() {
        Multimedia obj = dod.getRandomMultimedia();
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Multimedia' failed to provide an identifier", id);
        obj = multimediaRepository.findOne(id);
        multimediaRepository.delete(obj);
        multimediaRepository.flush();
        Assert.assertNull("Failed to remove 'Multimedia' with identifier '" + id + "'", multimediaRepository.findOne(id));
    }
    
}
