// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ve.gob.iribarren.tube.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ve.gob.iribarren.tube.model.YoutubeCanalDataOnDemand;
import ve.gob.iribarren.tube.model.YoutubeCanalIntegrationTest;
import ve.gob.iribarren.tube.repository.YoutubeCanalRepository;

privileged aspect YoutubeCanalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: YoutubeCanalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: YoutubeCanalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: YoutubeCanalIntegrationTest: @Transactional;
    
    @Autowired
    YoutubeCanalDataOnDemand YoutubeCanalIntegrationTest.dod;
    
    @Autowired
    YoutubeCanalRepository YoutubeCanalIntegrationTest.youtubeCanalRepository;
    
    @Test
    public void YoutubeCanalIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to initialize correctly", dod.getRandomYoutubeCanal());
        long count = youtubeCanalRepository.count();
        Assert.assertTrue("Counter for 'YoutubeCanal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void YoutubeCanalIntegrationTest.testFind() {
        YoutubeCanal obj = dod.getRandomYoutubeCanal();
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to provide an identifier", id);
        obj = youtubeCanalRepository.findOne(id);
        Assert.assertNotNull("Find method for 'YoutubeCanal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'YoutubeCanal' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void YoutubeCanalIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to initialize correctly", dod.getRandomYoutubeCanal());
        long count = youtubeCanalRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'YoutubeCanal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<YoutubeCanal> result = youtubeCanalRepository.findAll();
        Assert.assertNotNull("Find all method for 'YoutubeCanal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'YoutubeCanal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void YoutubeCanalIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to initialize correctly", dod.getRandomYoutubeCanal());
        long count = youtubeCanalRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<YoutubeCanal> result = youtubeCanalRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'YoutubeCanal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'YoutubeCanal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void YoutubeCanalIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to initialize correctly", dod.getRandomYoutubeCanal());
        YoutubeCanal obj = dod.getNewTransientYoutubeCanal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'YoutubeCanal' identifier to be null", obj.getId());
        try {
            youtubeCanalRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        youtubeCanalRepository.flush();
        Assert.assertNotNull("Expected 'YoutubeCanal' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void YoutubeCanalIntegrationTest.testDelete() {
        YoutubeCanal obj = dod.getRandomYoutubeCanal();
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'YoutubeCanal' failed to provide an identifier", id);
        obj = youtubeCanalRepository.findOne(id);
        youtubeCanalRepository.delete(obj);
        youtubeCanalRepository.flush();
        Assert.assertNull("Failed to remove 'YoutubeCanal' with identifier '" + id + "'", youtubeCanalRepository.findOne(id));
    }
    
}
